### ISSUE TITLE
Support conversion of `module.xml` files into AsciiDoc

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod2mn#25]
Each of these files represent a document:

* data/resource_docs/*/resource.xml
* data/modules/*/module.xml

We need to have a command that converts all of these into Metanorma AsciiDoc documents.

**Comment by ronaldtse** [comment]
Right now we support `data/resource_docs/*/resource.xml` but not `data/modules/*/module.xml`.

We need to support the modules.

**Comment by ronaldtse** [comment]
Please refer to https://github.com/metanorma/iso-10303-smrl/tree/main/reference-docs/SMRL_v8_rc5_N10480 for output of a "modules" document.

In `module.xml` files, you can find the part number, for example:
* data/modules/activity/module.xml

```xml
<module
   name="activity"
   name.french="Activit&#233;"
   part="1047"
   version="3"
   
   wg.number="8343"
   wg.number.supersedes="6847"
   wg.number.arm="2941"
   wg.number.mim="1157"   
   checklist.internal_review="7069"
   checklist.project_leader="0000"
   checklist.convener="0000"
   status="TS"
   language="E"
   publication.year="2014-02"
   publication.date="2014-02-01"
   published="y"
   previous.revision.year="2010-07" 
   previous.revision.cancelled="NO" 
   revision.complete="YES" 
   rcs.date="$Date: 2019/05/27 18:08:04 $"
   rcs.revision="$Revision: 1.59 $"
  development.folder="dvlp"
>
...
```

This is part "1047" which looks like this:
<img width="961" alt="Screenshot 2023-05-10 at 6 10 29 PM" src="https://github.com/metanorma/stepmod2mn/assets/11865/ddfc0d53-407f-4461-97b5-6ef6b2125485">

Then:

<img width="960" alt="Screenshot 2023-05-10 at 6 10 39 PM" src="https://github.com/metanorma/stepmod2mn/assets/11865/2e6feb2f-dadd-415e-a942-37b1c1ca6dfa">

Then:
<img width="960" alt="Screenshot 2023-05-10 at 6 10 56 PM" src="https://github.com/metanorma/stepmod2mn/assets/11865/bad40985-52d5-49f8-a5d5-2cb3532b7cd6">

**Comment by Intelligent2013** [comment]
For the conversion `resource.xml` into adoc I've adapted XSLTs from `iso-10303-stepmod-master/xsl/res_doc`.
For `module.xml` the XSLTs found in `iso-10303-stepmod-master/xsl`.
To do:
- [ ] compare XSLT between `iso-10303-stepmod-master/xsl/res_doc` and `iso-10303-stepmod-master/xsl`
- [ ] adapt XSLT in stepmod2mn or add new, based on comparison.

**Comment by Intelligent2013** [comment]
Testing results:
- [ ] missing line break between the sentences:
`This third edition cancels and replaces the second edition (ISO/TS 10303-1047:2010-07), which has been technically revised. A detailed description of the changes is provided in <<AnnexF>>
`
- [ ] wrong text in `00-introduction.adoc`:
`module, activity, activity assignment, activity relationshipNo ARM EXPRESS declarations `
- [ ] wrong text in `01-scope.adoc`:
`... action_assignment action_assignment action_assignment.assigned_action -> action action => executed_actionPATHapplied_action_assignment applied_action_assignment.items[i] -> action_itemsobject_role.nameISO 10303-41applied_action_assignment applied_action_assignment <= action_assignment action_assignment.role -> object_role object_role.name
- [ ] wrong line breaks in `02-normrefs.adoc`
```
* [[[010303000001,ISO 10303-1]]],
        
        
        _Industrial automation systems and integration — Product data representation and exchange
     — Part 1: Overview and fundamental principles_* [[[010303000011,ISO 10303-11]]],
        
        
        _Industrial automation systems and integration — Product data representation and exchange 
     — Part 11: Description methods: The EXPRESS language reference manual_* [[[010303000041,ISO 10303-41]]],
        
        
        _Industrial automation systems and integration — Product data representation and exchange 
     — Part 41: Integrated generic resource: Fundamentals of product description and support_
```
- [ ] error in `04-info_reqs.adoc`, and missing sub-sections:
`_Error q1: arm schema must start or end in_arm_`

- [ ] missing schema name in the titles in `92-identifier.adoc`
`====  schema identification`
Original HTML:
![image](https://github.com/metanorma/stepmod2mn/assets/5559926/d4220528-33f7-47ed-9a62-5c68f9a6e8c5)


- missing line breaks in the table markup in `95-listings.adoc`:
```
| 
            ARM short form EXPRESS
          | <<express:HTML>>| <<express:EXPRESS>>| ISO/TC 184/SC 4/WG 12 N2941| MIM short form EXPRESS| <<express:HTML>>| <<express:EXPRESS>>| ISO/TC 184/SC 4/WG 12 N1157|===
```

- missing line break in `97-change-history.adoc `:
`No ARM EXPRESS declarations and interface specifications have been added, removed or modified. Definition added for "Activity" and description of the "chosen_method" attribute of Activity clarified.[[change_3]]`

- no entries in `99-bibliography.adoc`

**Comment by Intelligent2013** [comment]
- [ ] id can't starts by digit:
`* [[[010303000011,ISO 10303-11]]],`

**Comment by Intelligent2013** [comment]
Errors in `05-mim.adoc`:
```
_Error Map26: executed_action not found in relevant schemas_


_Error Map26: action not found in relevant schemas_


_Error Map25B: action.description not found in relevant schemas_


_Error Map35: ERROR in subtyping in PATH: executed_action is not a subtype of action_
```

**Comment by Intelligent2013** [comment]
> Errors in `05-mim.adoc:`

the module `sect_5_mapping_check.xsl` is not workable:
- missing `../nav/xsl/mapping_parse.xsl` and `../nav/xsl/mim_tree.xsl`
- when missing xslt commented, then XMLSpy shows the error
![image](https://github.com/metanorma/stepmod2mn/assets/5559926/e3904460-d360-4e8e-9ff1-5204b35d6150)

This module is using for checking purposes only. I've commented the checking temporarily,

**Comment by Intelligent2013** [comment]
The figure references:
`93-arm-express-g.adoc`:
```adoc
The EXPRESS-G graphical notation is defined in ISO 10303-11.

[[armexpg]]

* <<Figure C.1 — ARM schema level EXPRESS-G diagram 1 of 1, ../armexpg1.xml>>

* <<Figure C.2 — ARM entity level EXPRESS-G diagram 1 of 1, ../armexpg2.xml>>
```
`94-mim-express-g.adoc`:
```adoc
The EXPRESS-G graphical notation is defined in ISO 10303-11.

[[mimexpg]]

* <<Figure D.1 — MIM schema level EXPRESS-G diagram 1 of 1, ../mimexpg1.xml>>

* <<Figure D.2 — MIM entity level EXPRESS-G diagram 1 of 1, ../mimexpg2.xml>>
```

should be transformed to (see https://github.com/metanorma/stepmod2mn/issues/14):
```
.MIM schema level EXPRESS-G diagram 1 of 1
image::../mimexpg1.xml[]
```

but may be later into like this:
```adoc
(*"action_schema.__expressg"
[.svgmap]
====
[[expg-action_schema-1]]
.EXPRESS-G diagram of the action_schema (1 of 2)
image::../../../../resources/action_schema/action_schemaexpg1.svg[]

* <<express:basic_attribute_schema>>; 1
* <<express:action_schema>>; 2
* <<express:support_resource_schema>>; 3
====
*)
```
I don't understand how to do it just now.

**Comment by Intelligent2013** [comment]
Metanorma XML generation issues:
```
Multiple instances of same ID: interfaces
```

From `04-info_reqs.adoc`:
```adoc
[[interfaces]]
== Required AM ARM
```

From `05-mim.adoc` (empty title?):
```adoc
[[interfaces]]
== 

```

```
Multiple instances of same ID: AnnexE
```
From `95-listings.adoc`:
```
[[AnnexE]]
[appendix,obligation=informative]
== Computer interpretable listings

[[AnnexE]]
[appendix,obligation=informative]
== Computer interpretable listings

```

**Comment by Intelligent2013** [comment]
`bundle exec metanorma -t iso -x presentation document.adoc` causes the error:
```
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/isodoc-2.5.5/lib/isodoc/presentation_function/refs.rb:97:in `bibliography_bibitem_number_insert_pt'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/isodoc-2.5.5/lib/isodoc/presentation_function/refs.rb:84:in `bibliography_bibitem_number1'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/isodoc-2.5.5/lib/isodoc/presentation_function/refs.rb:77:in `block in bibliography_bibitem_number'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/nokogiri-1.14.5-x64-mingw-ucrt/lib/nokogiri/xml/node_set.rb:235:in `block in each'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/nokogiri-1.14.5-x64-mingw-ucrt/lib/nokogiri/xml/node_set.rb:234:in `upto'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/nokogiri-1.14.5-x64-mingw-ucrt/lib/nokogiri/xml/node_set.rb:234:in `each'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/isodoc-2.5.5/lib/isodoc/presentation_function/refs.rb:76:in `bibliography_bibitem_number'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/isodoc-2.5.5/lib/isodoc/presentation_function/refs.rb:4:in `references'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/isodoc-2.5.5/lib/isodoc/presentation_xml_convert.rb:48:in `section'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/isodoc-2.5.5/lib/isodoc/presentation_xml_convert.rb:39:in `conversions'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/isodoc-2.5.5/lib/isodoc/presentation_xml_convert.rb:23:in `convert1'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-iso-2.4.4/lib/isodoc/iso/presentation_xml_convert.rb:18:in `convert1'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/isodoc-2.5.5/lib/isodoc/convert.rb:150:in `convert'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-iso-2.4.4/lib/metanorma/iso/processor.rb:67:in `output'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-1.5.10/lib/metanorma/compile.rb:159:in `process_output_unthreaded'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-1.5.10/lib/metanorma/compile.rb:145:in `process_exts1'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-1.5.10/lib/metanorma/compile.rb:119:in `process_ext'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-1.5.10/lib/metanorma/compile.rb:107:in `block in process_exts'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-1.5.10/lib/metanorma/compile.rb:106:in `each'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-1.5.10/lib/metanorma/compile.rb:106:in `process_exts'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-1.5.10/lib/metanorma/compile.rb:37:in `compile'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.2/lib/metanorma/cli/compiler.rb:45:in `compile_file'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.2/lib/metanorma/cli/compiler.rb:30:in `compile'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.2/lib/metanorma/cli/compiler.rb:35:in `compile'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.2/lib/metanorma/cli/command.rb:244:in `compile_document'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.2/lib/metanorma/cli/command.rb:48:in `block in compile'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.2/lib/metanorma/cli/command.rb:48:in `each'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.2/lib/metanorma/cli/command.rb:48:in `compile'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.2/lib/metanorma/cli.rb:34:in `start'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.2/exe/metanorma:25:in `block in <top (required)>'
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.2/exe/metanorma:43:in `<top (required)>'
C:/tools/ruby31/bin/metanorma:25:in `load'
C:/tools/ruby31/bin/metanorma:25:in `<main>'
undefined method `previous_element' for nil:NilClass

      unless ins = bibitem.at(ns(".//docidentifier")).previous_element
                                                     ^^^^^^^^^^^^^^^^^
```

**Comment by Intelligent2013** [comment]
The error occurs due the bold formatting inside express link:
```
... within an instance of <<express:*Activity_status*>>.
```

**Comment by Intelligent2013** [comment]
`module.xml` processing added. The issue post is too long. The further actions will be done in 
https://github.com/metanorma/stepmod2mn/issues/36 and https://github.com/metanorma/stepmod2mn/issues/37.
