### ISSUE TITLE
Error after xalan upgrade to 2.7.3

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/stepmod2mn#44]
`java -jar D:\Work\Metanorma\stepmod2mn\target\stepmod2mn-1.13.jar resource.xml`

causes the error:
```
stepmod2mn Input: XML (resource.xml)
Output: ADOC (D:\Work\Metanorma\Stepmod\iso-10303-stepmod-master\data\resource_docs\fundamentals_of_product_description_and_support\document.adoc)

Transforming...
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/xml/serializer/OutputPropertiesFactory
        at org.apache.xalan.templates.OutputProperties.<init>(OutputProperties.java:84)
        at org.apache.xalan.transformer.TransformerIdentityImpl.<init>(TransformerIdentityImpl.java:93)
        at org.apache.xalan.processor.TransformerFactoryImpl.newTransformer(TransformerFactoryImpl.java:818)
        at org.metanorma.stepmod2mn.processLinearizedXML(stepmod2mn.java:572)
        at org.metanorma.stepmod2mn.convertstepmod2mn(stepmod2mn.java:419)
        at org.metanorma.stepmod2mn.main(stepmod2mn.java:356)
Caused by: java.lang.ClassNotFoundException: org.apache.xml.serializer.OutputPropertiesFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 6 more

**Comment by Intelligent2013** [comment]
`pom.xml` updated.
