### ISSUE TITLE
Error: Could not find variable with the name of errors_fatal_log_filename

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/stepmod2mn#84]
Source issue: https://github.com/metanorma/annotated-express/issues/134

Error:
> Ignore document processing due the wrong attribute 'part' value: ''
> Input: XML (/Users/nickn/Documents/Arbeit/upwork/ribose/tmp/iso-10303-stepmod/data/modules/description_assignment/module.xml)
> Output: ADOC (/Users/nickn/Documents/Arbeit/upwork/ribose/tmp/iso-10303-stepmod/data/resource_docs/fundamentals_of_product_description_and_support iso-10303-stepmod/data/resource_docs/geometrically_bounded_2d_wireframe/modules/description_assignment/document.adoc)
> 
> Transforming...
> SystemId Unknown; Line #1124; Column #60; org.apache.xml.utils.WrappedRuntimeException: Could not find variable with the name of errors_fatal_log_filename
> java.lang.NullPointerException
> 	at org.metanorma.stepmod2mn.convertstepmod2mn(stepmod2mn.java:542)
> 	at org.metanorma.stepmod2mn.main(stepmod2mn.java:433)

**Comment by Intelligent2013** [comment]
Fixed.
